[packages.nu_plugin_clipboard]
repo = "https://github.com/FMotalleb/nu_plugin_clipboard.git"
type = "cargo-git"

[packages.nu_plugin_audio_hook]
repo = "https://github.com/FMotalleb/nu_plugin_audio_hook"
type = "cargo-git"

[packages.nu_plugin_emoji]
repo = "nu_plugin_emoji"
type = "crate"

[packages.nu_plugin_net]
repo = "nu_plugin_net"
type = "crate"

[packages.nu_plugin_highlight]
repo = "nu_plugin_highlight"
type = "crate"

[packages.nu_plugin_nupsql]
repo = "https://gitlab.com/HertelP/nu_plugin_nupsql.git"
type = "cargo-git"

[packages."bookmark_for_dir.nu"]
repo = "https://github.com/yh17549/nu-dir-bookmark.git*bookmark_for_dir.nu"
type = "git-script"

[packages."nufmt.nu"]
repo = "https://github.com/blindFS/topiary-nushell.git*nufmt.nu"
type = "git-script"
